name: Backend CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: backend/environment.yml
          activate-environment: aipb-py311
          use-mamba: true

      - name: Run tests
        run: pytest -q backend

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Build CPU Docker image
        run: docker build -f backend/Dockerfile -t aipb-api:cpu --target cpu backend

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          image-ref: aipb-api:cpu
